### ISSUE TITLE
postgres data type "float8" is not being handled

### ISSUE THREAD

**Issue by alenas** [atreeon/easy_orm#3]
Seems like postgres data type "float8" is not being handled.
Any reason for that?

**Comment by atreeon** [comment]
Hi, great you had a look at this project.  Not all the data types are handled as yet.  The ones supported are in `lookupDbType`.  Are you interested in the project enough to want me to add them in?  It is fairly easy to do but you are literally the first person to write an issue!  (I might work on it some more next week)

**Comment by alenas** [comment]
Yes, I saw that `lookupDbType` :D I think your orm is interesting if someone has some database structure already.

**Comment by atreeon** [comment]
Thanks alenas, I've made a couple of changes so float8 should be handled now.  I've been trying to work out what I do next, if anything!
